modLoader="javafml"
loaderVersion="${neoforgeVersionRange}"
license="NC-MIT"
issueTrackerURL="https://github.com/uebliche/mod-template/issues"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="Mod Template (NeoForge)"
description="Shared mod template wired for NeoForge"
displayTest="IGNORE_SERVER_VERSION"
authors="uebliche"

[[dependencies.${modId}]]
modId="neoforge"
mandatory=true
versionRange="${neoforgeVersionRange}"
ordering="NONE"
side="BOTH"

[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
