[versions]
slf4j = "1.7.36"
manifold = "2025.1.25"
apache_httpclient = "4.5.14"
shadow = "9.0.0-beta15"
manifold_plugin = "0.0.2-alpha"
blossom ="2.1.0"
paperweight = "1.7.7"
velocity_api = "3.3.0-SNAPSHOT"

[libraries]
apache-httpclient = { module = "org.apache.httpcomponents:httpclient", version.ref = "apache_httpclient" }
manifold = { module ="systems.manifold:manifold-preprocessor", version.ref = "manifold" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity_api" }

[plugins]
manifold = { id = "systems.manifold.manifold-gradle-plugin", version.ref = "manifold_plugin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
